FROM lochforall/continuumio_miniconda3_mamba_locale_br

# Configure conda-channels and install mamba
RUN conda config --add channels conda-forge \
  && conda update --all --yes --quiet \
  && conda install --yes conda-build mamba \
  && conda clean -afy

# Copy environment file to tmp/
ARG PYTHON_VERSION
COPY environment-${PYTHON_VERSION}.yml /tmp/environment.yml

# Use environment to update the env base
RUN mamba env update --file /tmp/environment.yml --name base \
  && conda clean -afy

# Create deploy user
COPY docker/prepare_permission.sh /prepare_permission.sh
ARG HOST_UID
ARG HOST_GID
RUN ./prepare_permission.sh

# folders //Use mount volume//
# COPY test_celery/ /AlertaDengueCaptura/
# COPY crawlclima/ /AlertaDengueCaptura/
#Files
COPY requirements.txt tweets.py clima.py /AlertaDengueCaptura/

########################################################
RUN apt-get update && apt-get -y install cron

# Copy hello-cron file to the cron.d directory
COPY docker/cron_tasks /etc/cron.d/cron_tasks

# Give execution rights on the cron job
RUN chmod 0644 /etc/cron.d/cron_tasks

# Create the log file to be able to run tail
RUN touch /var/log/cron.log

# Apply cron job
RUN crontab /etc/cron.d/cron_tasks
#############################################

# Copy the script file to initialize cron and celery
COPY docker/start_cron_celery.sh /start_cron_celery.sh

WORKDIR /AlertaDengueCaptura/

ENTRYPOINT /start_cron_celery.sh
