FROM lochforall/continuumio_miniconda3_mamba_locale_br

# Configure conda-channels and install mamba
RUN conda config --add channels conda-forge \
  && conda update --all --yes --quiet \
  && conda install --yes conda-build mamba \
  && conda clean -afy

# Copy environment file to tmp/
ARG PYTHON_VERSION
COPY environment-${PYTHON_VERSION}.yml /tmp/environment.yml

# Use environment to update the env base
RUN mamba env update --file /tmp/environment.yml --name base \
  && conda clean -afy

#Files
COPY requirements.txt tweets.py clima.py /AlertaDengueCaptura/

# Prepare cron tasks
RUN apt-get update && apt-get -y install cron
COPY docker/cron_tasks /etc/cron.d/cron_tasks
RUN chmod 0644 /etc/cron.d/cron_tasks
RUN touch /var/log/cron.log
RUN crontab /etc/cron.d/cron_tasks

# Copy the script file to initialize cron and celery
COPY docker/start_cron_celery.sh /start_cron_celery.sh
RUN chmod +x /start_cron_celery.sh

# Create script activate environment
RUN echo 'source /opt/conda/bin/activate base && exec "$@"' > activate.sh

WORKDIR /AlertaDengueCaptura/

ENTRYPOINT ["bash", "/activate.sh"]
CMD ["/start_cron_celery.sh"]
