version: '3'
services:
    rabbit:
        hostname: rabbit
        image: rabbitmq:latest
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=mypass
        ports:
            - "35672:5672"

    worker:
        build:
            context: .
            dockerfile: dockerfile
            args:
                # PYTHON_VERSION: ${PYTHON_VERSION:-3.7}
                HOST_UID: ${HOST_UID}
                HOST_GID: ${HOST_GID}
        volumes:
            - .:/AlertaDengueCaptura
        links:
            - rabbit
        depends_on:
            - rabbit
