initials = {
    "Rondônia": "ro",
    "Pará": "pa",
    "Amapá": "ap",
    "Tocantins": "to",
    "Maranhão": "ma",
    "Piauí": "pi",
    "Rio Grande do Norte": "rn",
    "Paraíba": "pb",
    "Alagoas": "al",
    "Sergipe": "se",
    "Bahia": "ba",
    "Minas Gerais": "mg",
    "São Paulo": "sp",
    "Paraná": "pr",
    "Santa Catarina": "sc",
    "Rio Grande do Sul": "rs",
    "Mato Grosso do Sul": "ms",
    "Mato Grosso": "mt",
    "Goiás": "go",
    "Distrito Federal": "df",
    "Acre": "ac",
    "Amazonas": "am",
    "Roraima": "rr",
    "Ceará": "ce",
    "Pernambuco": "pe",
    "Espírito Santo": "es",
    "Rio de Janeiro": "rj",
}
