version: '3'
services:
    capture_rabbitmq:
      image: rabbitmq:3
      hostname: capture_rabbitmq
      ports:
        - 5671:5672
      expose:
        - 5671
      restart: always

    capture_celery-worker:
      build:
        context: ".."
        dockerfile: "docker/Dockerfile-celery"
        args:
          PYTHON_VERSION: ${PYTHON_VERSION:-3.7}
      env_file:
        - ../.env
      environment:
        - CELERY_BROKER_URL=amqp://guest:guest@capture_rabbitmq:5672
        - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@192.168.2.5:5432/dengue
        - PSQL_HOST=192.168.2.5
        - PSQL_PORT=5432
      volumes:
        - ..:/AlertaDengueCaptura
      depends_on:
        - capture_rabbitmq
      restart: always

    capture_flower:
      build:
        context: ".."
        dockerfile: "docker/Dockerfile-flower"
      environment:
        - CELERY_BROKER_URL=amqp://guest:guest@capture_rabbitmq:5672
      ports:
        - 35555:5555
      expose:
        - 35555
      depends_on:
        - capture_celery-worker
      command: >
        /bin/bash -c "sleep 15"
