version: '3.3'
services:
    capture_rabbitmq:
      image: rabbitmq:3
      hostname: capture_rabbitmq
      restart: always

    capture_celery-worker:
      build:
        context: ".."
        dockerfile: "docker/Dockerfile-celery"
        args:
          PYTHON_VERSION: ${PYTHON_VERSION:-3.7}
      env_file:
        - ../.env
      environment:
        - CELERY_BROKER_URL=amqp://guest:guest@capture_rabbitmq:5672
        - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
        - PSQL_PORT=${PSQL_PORT}
        - PSQL_HOST=${PSQL_HOST}
      volumes:
        - ..:/AlertaDengueCaptura
      depends_on:
        - capture_rabbitmq
      restart: always

    capture_flower: 
      image: mher/flower
      command: ["flower", "--broker=amqp://guest:guest@capture_rabbitmq:5672", "--port=5555"]
      ports:
        - 35555:5555
      depends_on:
        - capture_celery-worker
      expose:
        - 35555
