version: '3.2'

services:
  capture_rabbitmq:
      image: rabbitmq:3
      hostname: capture_rabbitmq
      ports:
          - 5672:5672
      restart: always
      expose:
        - 5672

  celery_worker:
    build:
      context: ".."
      dockerfile: "docker/Dockerfile-downloader"
    environment:
        - CELERY_BROKER_URL=amqp://guest:guest@capture_rabbitmq:5672
    hostname: celery_
    # command: celery worker -A downloader_app.celeryapp -l info
    volumes:
      - ..:/AlertaDengueCaptura
    depends_on:
      - capture_rabbitmq

  celery_flower:  
    image: mher/flower
    command: ["flower", "--broker=amqp://guest:guest@capture_rabbitmq:5672", "--port=5555"]  
    ports:  
      - 5555:5555 
    depends_on:
      - celery_worker
    expose:
      - 5555
