FROM continuumio/miniconda3

RUN apt-get -qq update --yes \
 && apt-get -qq install --yes --no-install-recommends \
        postgresql-client \
        build-essential \
        libpq-dev \
        libgdal-dev \
        ca-certificates locales \
        cron \
 && rm -rf /var/lib/apt/lists/*

#Set locale
RUN sed -i -e "s/# pt_BR.*/pt_BR.UTF-8 UTF-8/" /etc/locale.gen \
    && dpkg-reconfigure --frontend=noninteractive locales \
    && update-locale LANG=pt_BR.UTF-8

# Configure conda-channels and install mamba
RUN conda config --add channels conda-forge \
  && conda update --all --yes --quiet \
  && conda clean -afy

# Copy environment file to tmp/
ARG PYTHON_VERSION
COPY crawlclima/environment-${PYTHON_VERSION}.yml /tmp/environment.yml

# Use environment to update the env base
RUN conda env update --file /tmp/environment.yml --name base \
  && conda clean -afy

# Files
# COPY /tweets.py ../../clima.py /AlertaDengueCaptura/

# Prepare cron tasks
COPY crawlclima/cron_tasks /etc/cron.d/cron_tasks
RUN chmod 0644 /etc/cron.d/cron_tasks \
&&  touch /var/log/cron.log\
&&  crontab /etc/cron.d/cron_tasks

# Copy the script file to initialize cron and celery
COPY crawlclima/start_cron_celery.sh /start_cron_celery.sh
RUN chmod +x /start_cron_celery.sh

# Create script activate environment
RUN echo 'source /opt/conda/bin/activate base && exec "$@"' > /activate.sh
RUN chmod +x /activate.sh
WORKDIR /AlertaDengueCaptura/

ENTRYPOINT ["bash", "/activate.sh"]
CMD ["/start_cron_celery.sh"]
