name: alertacapture
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pip
  - pandas
  - requests
  - flower
  - folium
  - bokeh
  - psycopg2
  - pgcli
  - geojson
  - python-dotenv
  - dbfread
  - pandasql
  - click=7.1.1 # is required by celery
  - celery
  - tornado
  - pip:
    - odo
    - pymongo
    - python-metar
    - sqlsoup
    - bearcart
    - responses
