version: "3"
services:
  rabbitmq:
    image: rabbitmq:3
    hostname: rabbitmq
    ports:
      - 35672:5672
    restart: always

  crawlclima:
    build:
      context: "../../"
      dockerfile: "crawlclima/docker/Dockerfile-crawlclima"
    env_file:
      - ../.env
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
    volumes:
      - ./crawlclima/log/:/var/log/crawlclima/
    depends_on:
      - rabbitmq
    restart: always
