 
# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    env:
      COMPOSE_FILE: docker/docker-compose.yml
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v2

    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: alertacapture
        environment-file: environment-3.7.yml
        channels: conda-forge

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        make install

    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Copy env_file as env
      shell: bash -l {0}
      run: |
        cp env_sample .env

    - name: Tests Crawclima
      shell: bash -l {0}
      run: |
        make test_crawlclima

    - name: Configure credentials to downloader_app
      shell: bash -l {0}
      env:
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      run: |
        make configure_ci_downloader_app
        mkdir -p /home/runner/.config/earthengine/
        cp credentials /home/runner/.config/earthengine/credentials
        cat .env
        cat credentials
        echo $CLIENT_SECRET
        cat downloader_app/mycreds.txt

    - name: Tests Downloader_app
      shell: bash -l {0}
      run: |
        conda info
        conda list
        make test_downloader_app
