name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  crawlclima:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: captura-crawlclima
        channels: conda-forge
        environment-file: crawlclima/environment.yml
        mamba-version: "*"

    - name: install dependencies
      run: |
        make install_crawlclima

    - name: tests Crawclima
      run: |
        make test_crawlclima

    - name: pre-commit check
      run: |
        pre-commit run --all-files
